name: Dynamically Notify Code Owners

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Notify Code Owners
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REQUESTED_REVIEWERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers | jq -c -r '.users[].login' | jq -s -r 'join(", ")')
          echo "Requested reviewers: $REQUESTED_REVIEWERS"
          MESSAGE="New Pull Request: *${PR_TITLE}* opened by ${PR_USER}\n${PR_URL}\n\nRequested reviewers: $REQUESTED_REVIEWERS"
          echo "Message: $MESSAGE"
          RESPONSE=$(curl -s -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL)
          BODY=$(echo $RESPONSE | sed -e 's/[0-9]*$//')
          STATUS=$(echo $RESPONSE | grep -o '[0-9]*$')
          echo "Response body: $BODY"
          echo "Response status: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "Error sending message to Slack: $BODY"
            exit 1
          fi