name: Notify Code Owners and Request Reviews on Slack

on:
  pull_request:
    types: [opened, synchronize] 

jobs:
  notify-and-request-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Determine Changed Files
        id: changed-files
        run: |
          base_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
          head_sha=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")
          changed_files=$(git diff --name-only $base_sha $head_sha)
          echo "::set-output name=changed_files::[$(echo $changed_files | jq -R -s 'split("\n") | .[:-1]')]"
      
      - name: Notify Code Owners and Request Reviews
        if: ${{ always() && steps.changed-files.outputs.changed_files }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          declare -A codeowners_map
          while read -r pattern owners; do
            codeowners_map["$pattern"]="$owners"
          done < CODEOWNERS
      
          changed_files=$(echo '${{ steps.changed-files.outputs.changed_files }}' | jq -r '.[]')
          declare -A unique_owners
      
          for file in $changed_files; do
            for pattern in "${!codeowners_map[@]}"; do
              if [[ "$file" == $pattern ]]; then
                for owner in ${codeowners_map[$pattern]}; do
                  unique_owners["$owner"]=1
                done
              fi
            done
          done
      
          if [[ ${#unique_owners[@]} -gt 0 ]]; then
            owners_list=$(printf "%s\n" "${!unique_owners[@]}" | jq -R 'split("\n") | .[:-1]')
            # Debugging
            echo "owners_list before jq: ${owners_list}" 
            pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            message="Please review the changes: $(echo $owners_list | jq -r '. | join(", ")')"
            escaped_message=$(printf '%s' "$message" | jq -aRs .)
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":$escaped_message\n<${{ github.event.pull_request.html_url }}|Pull Request #$pr_number>\"}" $SLACK_WEBHOOK_URL
          fi
      